Imports DevExpress.XtraCharts.Designer
Imports System.Windows.Forms

Namespace ChartDesignerRuntime
    Partial Public Class Form1
        Inherits DevExpress.XtraBars.Ribbon.RibbonForm

        Public Sub New()
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            productsTableAdapter1.Fill(nwindDataSet1.Products)
        End Sub

        Private Sub btnRunDesigner_ItemClick(ByVal sender As Object, ByVal e As DevExpress.XtraBars.ItemClickEventArgs) Handles btnRunDesigner.ItemClick
            Dim designer As New ChartDesigner(chartControl1)
            designer.ShowDialog()
        End Sub
    End Class
End Namespace
