using DevExpress.XtraCharts.Designer;
using System.Windows.Forms;

namespace ChartDesignerRuntime {
    public partial class Form1 : DevExpress.XtraBars.Ribbon.RibbonForm {
        public Form1() {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            productsTableAdapter1.Fill(nwindDataSet1.Products);
        }

        private void btnRunDesigner_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e) {
            ChartDesigner designer = new ChartDesigner(chartControl1);
            designer.ShowDialog();
        }
    }
}
